### ISSUE TITLE
Fix Packaging

### ISSUE THREAD

**Issue by rscnt** [NextStepWebs/codemirror-spell-checker#14]
This library is declared as a dependency by 'simplemde-markdown-editor', which is CommonJS compatible, except when it isn't, because src/js/spell-checker.js assumes there is a CodeMirror global, and that breaks the package 'simplemde-markdown-editor'.

I was going to make a fork, then a pull request later, but this guy [@universome ](https://github.com/universome/codemirror-spell-checker), has already fixed it...

**Comment by benrlodge** [comment]
@WesCossick do you plan on implementing this fix? I'm using simplemde and this project in one of mine (thanks) and right now my hack is to require the minified version, but gulp whines about that not being a good idea, re: https://github.com/NextStepWebs/simplemde-markdown-editor/issues/175

**Comment by WesCossick** [comment]
Yes, soonish. It's on my list to get done in the coming weeks.

**Comment by benrlodge** [comment]
awesome, thanks @WesCossick

**Comment by lpillonel** [comment]
By just adding  at the beginning in spell-checker.js :

```
var CodeMirror = require("codemirror");
var Typo = require("./typo");
```

and a `module.exports = Typo;` at the end of typo.js, it does the trick for me

**Comment by jstejada** [comment]
any updates on this?

**Comment by WesCossick** [comment]
@jstejada Pending time in my very busy schedule. As always, a PR will greatly expedite this issue.

**Comment by WesCossick** [comment]
This issue has been fixed via a redesigned way of loading CodeMirror Spell Checker. SimpleMDE will incorporate this fix very soon.
