### ISSUE TITLE
What is overlay.min.js

### ISSUE THREAD

**Issue by Codepadawan** [NextStepWebs/codemirror-spell-checker#31]
> Be sure to load/require overlay.min.js if you haven't already.

What is this? Where do I find it?

Or alternately, is there a way I can use your simplemde editor (which I use in one part of my project) to **just do the spellchecking and nothing else** in another part of my project? That'd be nice, since I then only have to load the one library, and simplemde seems to have everything out of the box.

**Comment by WesCossick** [comment]
The `overlay.min.js` file is provided by CodeMirror and allows a second parsing script to run, essentially. You can find it from their CDN or repository.

SimpleMDE cannot be used to just add spell checking capabilities to CodeMirror.
